---
homebrew_taps:
  - felixkratz/formulae
  - heroku/brew
  - homebrew/bundle
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/services
  - nikitabobko/tap
  - supabase/tap
homebrew_casks:
  - 1password
  - aerospace
  - alacritty
  - betterdisplay
  - chromedriver
  - docker
  - figma
  - httpie
  - hyperkey
  - jetbrains-toolbox
  - obsidian
  - raycast
  - scroll-reverser
  - zed
homebrew_packages:
  - bat
  - bottom
  - boxes
  - coreutils
  - direnv
  - felixkratz/formulae/borders
  - figlet
  - findutils
  - fish
  - fortune
  - fzf
  - gawk
  - gcc
  - gh
  - git-delta
  - gnu-sed
  - gnu-tar
  - gnu-which
  - go
  - grep
  - gzip
  - htop
  - jq
  - lazygit
  - lsd
  - luarocks
  - magic-wormhole
  - make
  - mise
  - mosh
  - neovim
  - openssh
  - pnpm
  - postgresql@15
  - prettier
  - rbenv
  - ripgrep
  - rust
  - shellcheck
  - starship
  - stow
  - supabase/tap/supabase
  - wget
  - xplr
  - zellij
  - zoxide
