---
- hosts: localhost
  vars_prompt:
    - name: wifi_ssid
      prompt: Enter your wifi SSID
      private: no
      default: ""

    - name: wifi_password
      prompt: Enter your wifi password
      private: no
      default: ""
  tasks:
    - name: Include macOS role
      include_role:
        name: macos
      when: ansible_os_family == "Darwin"

    - name: Include Arch Linux role
      include_role:
        name: arch
      when: ansible_facts['distribution'] == 'Archlinux'

    - name: Include common role
      include_role:
        name: common
