---
arch_packages:
  - 1password
  - alacritty
  - amd-ucode # TODO: check that the processor is AMD before installing
  - base
  - base-devel
  - bat
  - bind
  - blueman
  - bluez
  - bluez-utils
  - bottom
  - brightnessctl
  - copyq
  - ddcci-driver-linux-dkms
  - direnv
  - docker
  - docker-compose
  - dosfstools
  - efibootmgr
  - fd
  - firefox-developer-edition
  - fish
  - font-manager
  - fzf
  - gammastep-git
  - git
  - gnome-keyring
  - google-chrome
  - grub
  - htop
  - hyprcursor-git
  - hyprland-git
  - hyprlang-git
  - hyprwayland-scanner-git
  - inotify-tools
  - jellyfin-ffmpeg5-bin
  - jq
  - lazygit
  - libgnome-keyring
  - libva-mesa-driver
  - libva-utils
  - linux
  - linux-firmware
  - linux-headers
  - lsd
  - lvm2
  - magic-wormhole
  - mako
  - mise-bin
  - mpv
  - neofetch
  - neovim-git
  - networkmanager
  - os-prober
  - paru
  - pipewire-pulse
  - plocate
  - pnpm
  - postgresql
  - qt5-wayland
  - qt6-wayland
  - reflector
  - ripgrep
  - snapd
  - spdlog-git
  - starship
  - stow
  - supabase-git
  - swayidle
  - swww-git
  - sxiv-git
  - ttf-joypixels
  - unzip
  - vulkan-radeon # TODO: check if the GPU is AMD before installing
  - waybar-git
  - wev-git
  - wget
  - wl-clipboard
  - wlr-randr-git
  - wofi
  - zellij
  - zoxide
root_systemd_services:
  - bluetooth
  - NetworkManager
  - docker
  - snapd.socket
  - snapd.apparmor
user_systemd_services:
  - gnome-keyring-daemon
  - pipewire
  - pipewire-pulse
  - wireplumber
  - xdg-desktop-portal
  - mako
