---
dotfiles_dir: "{{ ansible_env.HOME }}/.dotfiles"
src_dir: "{{ ansible_env.HOME }}/src"
macos_dotfiles:
  - aerospace
linux_dotfiles:
  - hyprland
  - waybar
  - wireplumber
common_dotfiles:
  - alacritty
  - bin
  - bash
  - borders
  - git
  - lsd
  - nvim
  - starship
  - zellij
  - zsh
mise_runtimes:
  - python@3.12.2
  - ruby@3.2.3
  - node@20.4.0
  - erlang@27.0.1
  - elixir@1.17.2-otp-27
  - bun@1.1.4
